server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/election_monitor_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=9666
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/api

app.jwt.secret=ElectionMonitor2024SuperSecretKeyThatIsAtLeast256BitsLongForHS256Algorithm!
app.jwt.expiration-ms=86400000

app.cors.allowed-origins=http://localhost:5173

spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.username=dhanyaande@gmail.com
spring.mail.password=kxhfifxvlinprais
spring.mail.protocol=smtps
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.smtp.ssl.checkserveridentity=false
spring.mail.properties.mail.smtps.auth=true
spring.mail.properties.mail.smtps.ssl.enable=true
spring.mail.properties.mail.smtps.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.smtps.ssl.checkserveridentity=false
spring.mail.properties.mail.smtp.socketFactory.port=465
spring.mail.properties.mail.smtp.socketFactory.class=javax.net.ssl.SSLSocketFactory
spring.mail.properties.mail.smtp.socketFactory.fallback=false
spring.mail.properties.mail.smtp.connectiontimeout=10000
spring.mail.properties.mail.smtp.timeout=10000
spring.mail.properties.mail.smtp.writetimeout=10000
spring.mail.default-encoding=UTF-8
